version: 1
backend:
  phases:
    build:
      commands:
        - nvm install 22.17.1
        - nvm use 22.17.1
        - npm ci --silent
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 22.17.1
        - nvm use 22.17.1
        - npm ci --silent
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
